apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "01-md5sum-producer.fullname" . }}
  labels:
    {{- include "01-md5sum-producer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "01-md5sum-producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "01-md5sum-producer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "01-md5sum-producer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.localRepo }}

          image: "{{ .Values.image.localRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"         {{ else }}
          image: "{{ .Values.image.prodRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
                name: {{ .Values.configMapRef.name }}
          env:
            - name: MYENV_MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.MYENV_MY_NODE_NAME }}
            - name: MYENV_MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.MYENV_MY_POD_NAME }}
            - name: MYENV_MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.MYENV_MY_POD_NAMESPACE }}
            - name: MYENV_MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: {{ .Values.MYENV_MY_POD_IP }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.probes.liveness.path }}"
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.probes.readiness.path }}"
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
