apiVersion: v1
kind: Service
metadata:
  name: {{ include "01-md5sum-producer.fullname" . }}
  labels:
    {{- include "01-md5sum-producer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.metricsport.port }}
      targetPort: {{ .Values.metricsport.targetport }}
      nodePort: {{ .Values.metricsport.nodeport }}
      name: {{ .Values.metricsport.name }}
  selector:
    {{- include "01-md5sum-producer.selectorLabels" . | nindent 4 }}
